name: Daily build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'  # UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash
      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare publish directory
        run: |
          mkdir -p publish

      - name: Run adblock script
        run: |
          chmod +x ./scripts/adblock.sh
          ./scripts/adblock.sh > ./publish/adblock.hosts

      - name: Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
